config/routes.rb
Rails.application.routes.draw do
  # get 'orders/new'
  devise_for :users
  resources :orders, only: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Show Books
  root to: "books#index"
  get "/books", to: "books#index", as: "books"

  # Add book to list
  get "books/add", to: "books#add", as: "add_book_to_list"

  # Create new book
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"

  # Remove book entry on my list
  delete "books/:id", to: "book_list_items#destroy"

  # Show individual Book
  get "/books/:id", to: "books#show", as: "book"

  # Show Authors
  get "/authors", to: "authors#index", as: "authors"

  # Show individual Author
  get "/authors/:id", to: "authors#show", as: "author"

  #Show booklist items
  get "/mylist", to: "book_list_items#index", as: "book_list_items"

  # Edit for trade
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"

  #Create review
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "/reviews/", to: "reviews#create"

  #Order complete
  get "/orders/complete", to: "orders#complete"

  #Order Webhook
  post "/orders/webhook", to: "orders#webhook"
end

app/models/book_list_item.rb
class BookListItem < ApplicationRecord
  belongs_to :user
  belongs_to :book

  def self.contains?(current_user, book)
    return current_user.books.where(id: book.id).length > 0
  end

  def self.create_book_list_item(current_user, book)
    if (current_user.books.where(id: book.id).length == 0)
      current_user.books.push(book)
      current_user.save
    end
  end

  def self.book_list_item_id(current_user, book)
    return BookListItem.where("book_id = ? AND user_id = ?", book, current_user).first.id
  end

end

app/controllers/book_list_items_controller.rb
class BookListItemsController < ApplicationController
    
    before_action :authenticate_user!
    
    def index
        @books = current_user.books
    end

    def destroy
        item_id = BookListItem.book_list_item_id(current_user, params[:id])
        BookListItem.destroy(item_id)
        flash[:notice] = "Book was successfully removed from your list."
        redirect_to book_list_items_path
    end

    def edit
        @book_list_item = BookListItem.find(BookListItem.book_list_item_id(current_user, params[:id]))
    end

    def update
        @book_list_item = BookListItem.find(params[:id])
        @book_list_item.for_trade = params[:book_list_item][:for_trade]
        if @book_list_item.save
            redirect_to book_list_items_path
        end
    end

end

app/helpers/book_list_items_helper.rb
module BookListItemsHelper
end

app/views/book_list_items/edit.html.erb
<h2><%= @book_list_item.book.title %></h2>
<p><<%= @book_list_item.book.author.name %></p>

<%= form_with model: @book_list_item do |form| %>
    <p>
        <%= form.check_box :for_trade, value: @book_list_item.for_trade%>
        <%= label :for_trade, "Willing to trade" %>
    </p>

    <%= form.submit "Update" %>
<% end %>

app/views/book_list_items/index.html.erb
<h1>My Book List</h1>
<%= link_to 'Add a book', new_book_path, class:"btn btn-info"%>
<% @books.each do |book| %>
    <div class="row">
        <div class="col">
            <p><%= link_to book.title, book_path(book) %></p>
        </div>
        <div class="col">
            <p> <%= link_to 'Remove', book, method: "delete"%></p>
        </div>
        <div class="col">
            <p> <%= link_to 'Edit', edit_book_list_item_path(book) %></p>
        </div>
    </div>
<%  end  %>