config/routes.rb
Rails.application.routes.draw do
  # get 'orders/new'
  devise_for :users
  resources :orders, only: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Show Books
  root to: "books#index"
  get "/books", to: "books#index", as: "books"

  # Add book to list
  get "books/add", to: "books#add", as: "add_book_to_list"

  # Create new book
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"

  # Remove book entry on my list
  delete "books/:id", to: "book_list_items#destroy"

  # Show individual Book
  get "/books/:id", to: "books#show", as: "book"

  # Show Authors
  get "/authors", to: "authors#index", as: "authors"

  # Show individual Author
  get "/authors/:id", to: "authors#show", as: "author"

  #Show booklist items
  get "/mylist", to: "book_list_items#index", as: "book_list_items"

  # Edit for trade
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"

  #Create review
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "/reviews/", to: "reviews#create"

  #Order complete
  get "/orders/complete", to: "orders#complete"

  #Order Webhook
  post "/orders/webhook", to: "orders#webhook"
end

app/views/partials/_sidenav.html.erb
<nav class="col-2">
<h3>Menu</h3>
    <% if user_signed_in? %>
        <p><%= link_to "My List", book_list_items_path%></p>
    <% end %>
    <p><%= link_to "Home", root_path %></p>
    <p><%= link_to "Books", books_path %></p>
    <p><%= link_to "Authors", authors_path %></p>
</nav>

app/views/partials/_topnav.html.erb
<header class="top-nav row align-items-end">
    <div class="col text-right">
        <% if user_signed_in? %>
            <div id="logout"><%= link_to 'Logout ', destroy_user_session_path, method: "delete", class:"btn btn-warning"%></div>
            <div id="username"><%= current_user.email %></div>
        <% else %>
            <p><%= link_to 'Login', new_user_session_path, class:"btn btn-primary"%>
            <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-success"%>
            </p>
        <% end %>
    </div>
</header>