config/routes.rb
Rails.application.routes.draw do
  # get 'orders/new'
  devise_for :users
  resources :orders, only: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Show Books
  root to: "books#index"
  get "/books", to: "books#index", as: "books"

  # Add book to list
  get "books/add", to: "books#add", as: "add_book_to_list"

  # Create new book
  get "/books/new", to: "books#new", as: "new_book"
  post "/books", to: "books#create"

  # Remove book entry on my list
  delete "books/:id", to: "book_list_items#destroy"

  # Show individual Book
  get "/books/:id", to: "books#show", as: "book"

  # Show Authors
  get "/authors", to: "authors#index", as: "authors"

  # Show individual Author
  get "/authors/:id", to: "authors#show", as: "author"

  #Show booklist items
  get "/mylist", to: "book_list_items#index", as: "book_list_items"

  # Edit for trade
  get "/mylist/:id/edit", to: "book_list_items#edit", as: "edit_book_list_item"
  put "/mylist/:id", to: "book_list_items#update"
  patch "/mylist/:id", to: "book_list_items#update", as: "book_list_item"

  #Create review
  get "/reviews/new", to: "reviews#new", as: "new_review"
  post "/reviews/", to: "reviews#create"

  #Order complete
  get "/orders/complete", to: "orders#complete"

  #Order Webhook
  post "/orders/webhook", to: "orders#webhook"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_list_items
  has_many :reviews
  has_one_attached :picture

  def self.order_by_author_title
    books = []
    Author.all.order(:last_name).each do | author |
      books += author.books.order(:title)
    end
    return books
  end

  def self.find_book(title, author_last_name)
    book = nil
    books = Book.where("LOWER(title) = ?", title.downcase.strip)
    if (books)
      book = books.first
        if (book && book.author.last_name.downcase != author_last_name.downcase.strip)
          book = nil
        end
    end
    return book
  end

  def self.create_book(title, author, genre, picture, price)
    book = Book.find_book(title, author.last_name)
    if (!book)
      book = Book.new(title: title, genre: genre, author_id: author.id, price: price)
      book.picture.attach(picture)
      book.save
    end
    return book
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.order_by_author_title
    end

    def show
        @book = Book.find(params[:id])
        @can_add = !BookListItem.contains?(current_user, @book) if user_signed_in?
        @reviews = @book.reviews
        @rating = Review.get_average_rating(@book)
    end

    def add
        book = Book.find(params[:id])
        current_user.books.push(book)
        if current_user.save
            flash[:notice] = "Success! That book has been added to your list."
            redirect_to book_list_items_path 
        else
            flash[:alert] = "Oops! There was a problem adding that book to your list."
            redirect_back(fallback_location books_path)
        end
    end

    def new
        @book = Book.new
    end

    def create
        author = Author.create_author(params[:book][:first_name], params[:book][:last_name])
        book = Book.create_book(params[:book][:title], author, params[:book][:genre], params[:book][:picture], params[:book][:price])
        BookListItem.create_book_list_item(current_user, book)
        rescue
            flash[:alert] = "Oops! There was a problem adding that book."
            # redirect_back(fallback_location: books_path)
        ensure
            redirect_to book_list_items_path
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h2>Books</h2>
<%= image_tag 'clipart.png', alt:"Open book image"%>
<%if @books %>
    <% @books.each do |book|%>
        <p><%= link_to book.title, book_path(book) %></p>
        <p><%=book.author.name%></p>
    <%end%>
<%end%>

app/views/books/new.html.erb
<%= form_with model: @book do |form| %>
    <p>
        <%= label(:title, "Title") %>
        <%= form.text_field :title, required: true, minlength: 1 %>
    </p>
    <p>
        <%= label(:genre, "Genre") %>
        <%= form.text_field :genre %>
    </p>

    <p>
       <%= form.label :picture %>
       <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
    </p>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0, step: "0.01" %>
    <p>Author</p>
    <p>
        <%= label(:first_name, "First Name") %>
        <%= form.text_field :first_name %>
    </p>
    <p>
        <%= label(:last_name, "Last Name") %>
        <%= form.text_field :last_name, required: true, minlength: 1 %>
    </p>
    <%= form.submit "Add Book", class: "btn btn-success" %>
<% end %>

app/views/books/show.html.erb
<h2><%= @book.title%></h2>
<%= image_tag @book.picture, class: "img-thumbnail box", width: 120 if @book.picture.attached? %>
<% if user_signed_in? %>
    <% if @can_add %>
        <p> <%= link_to "Add to my list", add_book_to_list_path(id: @book), class: "btn btn-info" %></p>
    <% else %>
        <p> <%= link_to 'Remove from my list', @book, method: "delete", class: "btn btn-danger"%></p>
    <% end %>
<% end %>
<p><%= @book.author.name%></p>
<p><%= @book.genre%></p>
<% if @book.price %>
    <p><%= number_to_currency @book.price %></p>
    <%= link_to "Buy Now", new_order_path(book_id: @book.id), class: "btn btn-info" %>
<% end  %>
<hr/>
    <div>
        <h4>Review</h4>
        <% if user_signed_in? %>
        <%= link_to "Add Review", new_review_path(book: @book), class: "btn btn-primary" %>
        <% end %>
        <p>Overall Rating: <%= @rating %></p>
        <% if @reviews%>
            <% @reviews.each do |review| %>
            <div>
                <p class="rating"><%= "Rating: #{review.rating}" %></p>
                <p><%= review.user.email %></p>
                <p><%= review.comment %></p>
            </div>
            <% end %>
        <% end %>
    </div>
<hr/>

<p><%= link_to "Back", :back %></p>